export const addTodo = "ADD_TODO"
export const removeTodo = "REMOVE_TODO"
export const doTodo = "DO_TODO"
export const inCompelte = "INCOMPELETE_ITEMS"
export const AllTodo = "ALL_TODO"
export const completed = "COMPELETED"